spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatting?serverTimezone=UTC&characterEncoding=UTF-8
    username: extract
    password: Lodong8881@
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
server:
  port: 13883